
///////////////////////////////////////////////////////////////////////////
//
// Generated by MyGeneration Version # (1.3.0.9) 
// 
// Template Creado por:
//
// eXimo - Consultora en Sistemas
//
///////////////////////////////////////////////////////////////////////////

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Eximo.dal.SqlServerLibrary;

namespace Eximo.Log
{
	public class ERRORImpl	
	{
		#region ERROR methods

		public int ERRORAdd(ERROR error)
		{
			try
			{
				return (int)SqlHelper.ExecuteScalar(SqlImplHelper.getConnectionString(), "ERRORAdd",
                                                        error.Fecha,
                                                        error.TargetSite,
														error.Funcion, 
														error.Mensaje, 
														error.Modulo, 
														error.Tipo, 
														error.Componente, 
														error.Usuario, 
														error.Parametros,
                                                        error.Ip,
                                                        error.Host);
			}
			catch(Exception ex)
			{
				throw ex;
			}
		}

		#endregion
	}
}
