
///////////////////////////////////////////////////////////////////////////
//
// Generated by MyGeneration Version # (1.3.0.9) 
// 
// Template Creado por:
//
// eXimo - Consultora en Sistemas
//
///////////////////////////////////////////////////////////////////////////


using System;
using System.Data;
using System.Web;
using System.Collections.Generic;

namespace Eximo.Log
{
	public class ERRORBus
	{
		#region Business

		public int ERRORAdd(ERROR error)
		{
            try
            {
                if (HttpContext.Current.Session["idUsuario"] != null)
                {
                    error.Usuario = int.Parse(HttpContext.Current.Session["idUsuario"].ToString());
                    error.Ip = HttpContext.Current.Session["ip"].ToString();
                    error.Host = HttpContext.Current.Session["host"].ToString();
                    ERRORImpl oERRORImpl = new ERRORImpl();
                    return oERRORImpl.ERRORAdd(error);
                }
                else
                {
                    return 0;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
		}

        #endregion
	}
}
